### ISSUE TITLE
M1 still have issues using lightGBM

### ISSUE THREAD

**Issue by chen-bowen** [iusztinpaul/energy-forecasting#12]
When I ran the `bash scripts/install_poetry_macos_m1_chip.sh`
I get the following error
```
Error: Failed to load cask: librdkafka.rb
Cask 'librdkafka' is unreadable: wrong constant name #<Class:0x00000001362484e8>
```
When I ran lightGBM, it's getting the following error
```
Traceback (most recent call last):
  File "/Users/bowen.chen/opt/anaconda3/envs/energy_forecasting_feature_pipeline/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/bowen.chen/opt/anaconda3/envs/energy_forecasting_feature_pipeline/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/bowen.chen/LLM/energy-forecasting/training-pipeline/training_pipeline/hyperparameter_tuning.py", line 18, in <module>
    from training_pipeline.models import build_model
  File "/Users/bowen.chen/LLM/energy-forecasting/training-pipeline/training_pipeline/models.py", line 1, in <module>
    import lightgbm as lgb
  File "/Users/bowen.chen/opt/anaconda3/envs/energy_forecasting_feature_pipeline/lib/python3.9/site-packages/lightgbm/__init__.py", line 8, in <module>
    from .basic import Booster, Dataset, Sequence, register_logger
  File "/Users/bowen.chen/opt/anaconda3/envs/energy_forecasting_feature_pipeline/lib/python3.9/site-packages/lightgbm/basic.py", line 110, in <module>
    _LIB = _load_lib()
  File "/Users/bowen.chen/opt/anaconda3/envs/energy_forecasting_feature_pipeline/lib/python3.9/site-packages/lightgbm/basic.py", line 101, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/Users/bowen.chen/opt/anaconda3/envs/energy_forecasting_feature_pipeline/lib/python3.9/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
  File "/Users/bowen.chen/opt/anaconda3/envs/energy_forecasting_feature_pipeline/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/bowen.chen/opt/anaconda3/envs/energy_forecasting_feature_pipeline/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: <D21A7969-4567-3BC7-94ED-6A9E83AE9D78> /Users/bowen.chen/opt/anaconda3/envs/energy_forecasting_feature_pipeline/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so
  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)
```

Is there anything I did wrong?

**Comment by iusztinpaul** [comment]
Sorry to hear that. Unfortunately, I can't help you with this as I don't have a M1/M2 machine.

@gao-hongnan wrote the file.

@gao-hongnan Sorry to bother you, but could you please take a look at this issue to help us out?

**Comment by gao-hongnan** [comment]
@iusztinpaul Yes sure!

@chen-bowen May I confirm with you the following (assuming you have [Homebrew](https://brew.sh/) installed first):

1. Did the script continue to run? The first error is related to the installation of `hopswork` as the solution proposed is to build from source at a particular version. The error is because homebrew is treating `librdkafka` as a package instead of a cask.
2. Your error seems to be about `lightgbm`, can you try to do `brew install cmake` and `brew install libomp`?  The solution inside the script follows from the reference [here](https://stackoverflow.com/questions/72285089/i-am-not-able-to-run-lightgbm-on-mac-because-of-an-oserror-libomp-dylib-no-su).

If after brew installing both packages still result in an error, could you paste a more detailed log, thanks!

**Comment by iusztinpaul** [comment]
@gao-hongnan Thank you for your help ✌️

**Comment by chen-bowen** [comment]
looks like it worked with manually install cmake and libmop, thank you so much!
