### ISSUE TITLE
Error while running ml_pipeline DAG

### ISSUE THREAD

**Issue by VATUL123** [iusztinpaul/energy-forecasting#16]
@iusztinpaul 
Getting the following error while running the ml_pipeline DAG. I am on Mac M1.

3fbd685c2f7e
*** Found local files:
***   * /opt/airflow/logs/dag_id=ml_pipeline/run_id=manual__2023-08-21T13:03:22.018425+00:00/task_id=run_feature_pipeline/attempt=1.log
[2023-08-21, 13:03:25 UTC] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.run_feature_pipeline manual__2023-08-21T13:03:22.018425+00:00 [queued]>
[2023-08-21, 13:03:25 UTC] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.run_feature_pipeline manual__2023-08-21T13:03:22.018425+00:00 [queued]>
[2023-08-21, 13:03:25 UTC] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-21, 13:03:25 UTC] {taskinstance.py:1327} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): run_feature_pipeline> on 2023-08-21 13:03:22.018425+00:00
[2023-08-21, 13:03:25 UTC] {standard_task_runner.py:57} INFO - Started process 622 to run task
[2023-08-21, 13:03:25 UTC] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'run_feature_pipeline', 'manual__2023-08-21T13:03:22.018425+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmp1avv9lk_']
[2023-08-21, 13:03:25 UTC] {standard_task_runner.py:85} INFO - Job 7: Subtask run_feature_pipeline
[2023-08-21, 13:03:25 UTC] {task_command.py:410} INFO - Running <TaskInstance: ml_pipeline.run_feature_pipeline manual__2023-08-21T13:03:22.018425+00:00 [running]> on host 3fbd685c2f7e
[2023-08-21, 13:03:25 UTC] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='run_feature_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2023-08-21T13:03:22.018425+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-21T13:03:22.018425+00:00'
[2023-08-21, 13:03:25 UTC] {process_utils.py:181} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvh_7hgdul --system-site-packages --python=python3.9
[2023-08-21, 13:03:25 UTC] {process_utils.py:185} INFO - Output:
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO - created virtual environment CPython3.9.2.final.0-64 in 574ms
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -   creator CPython3Posix(dest=/tmp/venvh_7hgdul, clear=False, no_vcs_ignore=False, global=True)
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -     added seed packages: pip==23.1, setuptools==67.6.1, wheel==0.40.0
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-08-21, 13:03:27 UTC] {process_utils.py:181} INFO - Executing cmd: /tmp/venvh_7hgdul/bin/pip install -r /tmp/venvh_7hgdul/requirements.txt
[2023-08-21, 13:03:27 UTC] {process_utils.py:185} INFO - Output:
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO - Traceback (most recent call last):
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -   File "/tmp/venvh_7hgdul/bin/pip", line 5, in <module>
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -     from pip._internal.cli.main import main
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -   File "/tmp/venvh_7hgdul/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 9, in <module>
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -     from pip._internal.cli.autocompletion import autocomplete
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -   File "/tmp/venvh_7hgdul/lib/python3.9/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -     from pip._internal.cli.main_parser import create_main_parser
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -   File "/tmp/venvh_7hgdul/lib/python3.9/site-packages/pip/_internal/cli/main_parser.py", line 9, in <module>
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -     from pip._internal.build_env import get_runnable_pip
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -   File "/tmp/venvh_7hgdul/lib/python3.9/site-packages/pip/_internal/build_env.py", line 19, in <module>
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -     from pip._internal.cli.spinners import open_spinner
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -   File "/tmp/venvh_7hgdul/lib/python3.9/site-packages/pip/_internal/cli/spinners.py", line 9, in <module>
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -     from pip._internal.utils.logging import get_indentation
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -   File "/tmp/venvh_7hgdul/lib/python3.9/site-packages/pip/_internal/utils/logging.py", line 29, in <module>
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -     from pip._internal.utils.misc import ensure_dir
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -   File "/tmp/venvh_7hgdul/lib/python3.9/site-packages/pip/_internal/utils/misc.py", line 44, in <module>
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -     from pip._internal.locations import get_major_minor_version
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -   File "/tmp/venvh_7hgdul/lib/python3.9/site-packages/pip/_internal/locations/__init__.py", line 66, in <module>
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -     from . import _distutils
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -   File "/tmp/venvh_7hgdul/lib/python3.9/site-packages/pip/_internal/locations/_distutils.py", line 20, in <module>
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO -     from distutils.cmd import Command as DistutilsCommand
[2023-08-21, 13:03:27 UTC] {process_utils.py:189} INFO - ModuleNotFoundError: No module named 'distutils.cmd'
[2023-08-21, 13:03:27 UTC] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 374, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 575, in execute_callable
    pip_install_options=self.pip_install_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/python_virtualenv.py", line 99, in prepare_virtualenv
    execute_in_subprocess(pip_cmd)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/process_utils.py", line 170, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/process_utils.py", line 193, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venvh_7hgdul/bin/pip', 'install', '-r', '/tmp/venvh_7hgdul/requirements.txt']' returned non-zero exit status 1.
[2023-08-21, 13:03:27 UTC] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=run_feature_pipeline, execution_date=20230821T130322, start_date=20230821T130325, end_date=20230821T130327
[2023-08-21, 13:03:27 UTC] {standard_task_runner.py:109} ERROR - Failed to execute job 7 for task run_feature_pipeline (Command '['/tmp/venvh_7hgdul/bin/pip', 'install', '-r', '/tmp/venvh_7hgdul/requirements.txt']' returned non-zero exit status 1.; 622)
[2023-08-21, 13:03:27 UTC] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-21, 13:03:27 UTC] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check

**Comment by iusztinpaul** [comment]
It looks like it hasn't found the `distutils.cmd` module: `ModuleNotFoundError: No module named 'distutils.cmd'`

How did you run Airflow? Have you used our custom Airflow docker image?

Also, maybe this link will help: https://askubuntu.com/questions/1239829/modulenotfounderror-no-module-named-distutils-util

Here is our custom Docker image: https://github.com/iusztinpaul/energy-forecasting/blob/main/airflow/Dockerfile

**Comment by VATUL123** [comment]
Yeah, I followed this:

```
cd airflow
mkdir -p ./logs ./plugins
sudo chmod 777 ./logs ./plugins
echo -e "AIRFLOW_UID=$(id -u)" > .env
echo "ML_PIPELINE_ROOT_DIR=/opt/airflow/dags" >> .env
```
then

```
cd ./dags
cp .env.default .env
mkdir -p credentials/gcp/energy_consumption
cp -r /path/to/admin/gcs/credentials/admin-buckets.json credentials/gcp/energy_consumption
```

and then

```
cd ..
docker compose up airflow-init
docker compose --env-file .env up --build -d
```

**Comment by iusztinpaul** [comment]
I updated the Docker and Docker compose files under the Airflow directory.

Try to rerun the code with them, and let me know how it works.

Also, be careful not to copy paste all of the CLI commands you showed me above, as you have to adapt some placeholders with your particular files.
