### ISSUE TITLE
Fail when run the pipeline because cannot install requiment.txt

### ISSUE THREAD

**Issue by sonnh-uit** [iusztinpaul/energy-forecasting#18]
Hello guy, I am running the pipeline in the first time following guide in https://github.com/iusztinpaul/energy-forecasting#run. When I click button `RUN` in the Airflow, the pipeline fail in first task: run_feature_pipeline. I located the log and it say:
```
[2023-10-07, 03:57:40 UTC] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.2 -> 23.2.1
[2023-10-07, 03:57:40 UTC] {process_utils.py:190} INFO - [notice] To update, run: /tmp/venvhe33wlw9/bin/python -m pip install --upgrade pip
[2023-10-07, 03:57:40 UTC] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 395, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 594, in execute_callable
    prepare_virtualenv(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/python_virtualenv.py", line 99, in prepare_virtualenv
    execute_in_subprocess(pip_cmd)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/process_utils.py", line 171, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/process_utils.py", line 194, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venvhe33wlw9/bin/pip', 'install', '-r', '/tmp/venvhe33wlw9/requirements.txt']' returned non-zero exit status 1.
[2023-10-07, 03:57:40 UTC] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=run_feature_pipeline, execution_date=20231007T034621, start_date=20231007T035737, end_date=20231007T035740
[2023-10-07, 03:57:40 UTC] {standard_task_runner.py:104} ERROR - Failed to execute job 82 for task run_feature_pipeline (Command '['/tmp/venvhe33wlw9/bin/pip', 'install', '-r', '/tmp/venvhe33wlw9/requirements.txt']' returned non-zero exit status 1.; 69)
[2023-10-07, 03:57:40 UTC] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-07, 03:57:40 UTC] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
```
As follow this bug, I think the problem come from venv create by Airflow. Have anyone met this issue and how can I fix it?

**Comment by iusztinpaul** [comment]
Hello @sonnh-uit, have you set up the credentials for the private PiPy repository and ran the following commands?

```
# Set the experimental installer of Poetry to False. For us, it crashed when it was on True.
poetry config experimental.new-installer false
# Build & deploy the pipelines modules.
sh deploy/ml-pipeline.sh
```

**Comment by sonnh-uit** [comment]
> Hello @sonnh-uit, have you set up the credentials for the private PiPy repository and ran the following commands?
> 
> ```
> # Set the experimental installer of Poetry to False. For us, it crashed when it was on True.
> poetry config experimental.new-installer false
> # Build & deploy the pipelines modules.
> sh deploy/ml-pipeline.sh
> ```

Thanks for your support. I forgot these command when move project to the venv. I do that and it was better.
