### ISSUE TITLE
[TypeError] Error while running Feature-pipeline with Airflow

### ISSUE THREAD

**Issue by minhct13** [iusztinpaul/energy-forecasting#22]
Hi guys, I'm getting the error while running the feature-pipeline on Airflow, I've followed the instructions as https://github.com/iusztinpaul/energy-forecasting#run and stuck here, the logs was look like this:

[2023-10-26, 21:48:13 +07] {process_utils.py:182} INFO - Executing cmd: /tmp/venvyb53_u_a/bin/python /tmp/venvyb53_u_a/script.py /tmp/venvyb53_u_a/script.in /tmp/venvyb53_u_a/script.out /tmp/venvyb53_u_a/string_args.txt /tmp/venvyb53_u_a/termination.log
[2023-10-26, 21:48:13 +07] {process_utils.py:186} INFO - Output:
[2023-10-26, 21:48:18 +07] {process_utils.py:190} INFO - INFO:__main__:export_end_datetime = 2023-10-26 14:46:59
[2023-10-26, 21:48:18 +07] {process_utils.py:190} INFO - INFO:__main__:days_delay = 15
[2023-10-26, 21:48:18 +07] {process_utils.py:190} INFO - INFO:__main__:days_export = 30
[2023-10-26, 21:48:18 +07] {process_utils.py:190} INFO - INFO:__main__:url = https://drive.google.com/uc?export=download&id=1y48YeDymLurOTUO-GeFOUXVNc9MCApG5
[2023-10-26, 21:48:18 +07] {process_utils.py:190} INFO - INFO:__main__:feature_group_version = 1
[2023-10-26, 21:48:18 +07] {process_utils.py:190} INFO - INFO:feature_pipeline.pipeline:Extracting data from API.
[2023-10-26, 21:48:18 +07] {process_utils.py:190} INFO - WARNING:feature_pipeline.etl.extract:We clapped 'export_end_reference_datetime' to 'datetime(2023, 6, 30) + datetime.timedelta(days=days_delay)' as         the dataset will not be updated starting from July 2023. The dataset will expire during 2023.         Check out the following link for more information: https://www.energidataservice.dk/tso-electricity/ConsumptionDE35Hour
[2023-10-26, 21:48:18 +07] {process_utils.py:190} INFO - INFO:feature_pipeline.etl.extract:Data already downloaded at: /opt/***/dags/output/data/ConsumptionDE35Hour.csv
[2023-10-26, 21:48:19 +07] {process_utils.py:190} INFO - INFO:feature_pipeline.pipeline:Successfully extracted data from API.
[2023-10-26, 21:48:19 +07] {process_utils.py:190} INFO - INFO:feature_pipeline.pipeline:Transforming data.
[2023-10-26, 21:48:19 +07] {process_utils.py:190} INFO - INFO:feature_pipeline.pipeline:Successfully transformed data.
[2023-10-26, 21:48:19 +07] {process_utils.py:190} INFO - INFO:feature_pipeline.pipeline:Building validation expectation suite.
[2023-10-26, 21:48:19 +07] {process_utils.py:190} INFO - INFO:feature_pipeline.pipeline:Successfully built validation expectation suite.
[2023-10-26, 21:48:19 +07] {process_utils.py:190} INFO - INFO:feature_pipeline.pipeline:Validating data and loading it to the feature store.
[2023-10-26, 21:48:19 +07] {process_utils.py:190} INFO - Connected. Call `.close()` to terminate connection gracefully.
[2023-10-26, 21:48:21 +07] {process_utils.py:190} INFO - 
[2023-10-26, 21:48:21 +07] {process_utils.py:190} INFO - 
[2023-10-26, 21:48:21 +07] {process_utils.py:190} INFO - UserWarning: The installed hopsworks client version 3.2.0 may not be compatible with the connected Hopsworks backend version 3.4.1.
[2023-10-26, 21:48:21 +07] {process_utils.py:190} INFO - To ensure compatibility please install the latest bug fix release matching the minor version of your backend (3.4) by running 'pip install hopsworks==3.4.*'
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO - 
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO - Logged in to project, explore it here https://c.app.hopsworks.ai:443/p/140438
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO - Connected. Call `.close()` to terminate connection gracefully.
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO - Traceback (most recent call last):
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO -   File "/tmp/venvyb53_u_a/script.py", line 90, in <module>
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO -     res = run_feature_pipeline(*arg_dict["args"], **arg_dict["kwargs"])
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO -   File "/tmp/venvyb53_u_a/script.py", line 81, in run_feature_pipeline
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO -     return pipeline.run(
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO -   File "/tmp/venvyb53_u_a/lib/python3.9/site-packages/feature_pipeline/pipeline.py", line 61, in run
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO -     load.to_feature_store(
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO -   File "/tmp/venvyb53_u_a/lib/python3.9/site-packages/feature_pipeline/etl/load.py", line 24, in to_feature_store
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO -     feature_store = project.get_feature_store()
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO -   File "/tmp/venvyb53_u_a/lib/python3.9/site-packages/hopsworks/project.py", line 111, in get_feature_store
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO -     return connection(
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO -   File "/tmp/venvyb53_u_a/lib/python3.9/site-packages/hsfs/decorators.py", line 35, in if_connected
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO -     return fn(inst, *args, **kwargs)
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO -   File "/tmp/venvyb53_u_a/lib/python3.9/site-packages/hsfs/connection.py", line 178, in get_feature_store
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO -     return self._feature_store_api.get(util.rewrite_feature_store_name(name))
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO -   File "/tmp/venvyb53_u_a/lib/python3.9/site-packages/hsfs/core/feature_store_api.py", line 35, in get
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO -     return FeatureStore.from_response_json(
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO -   File "/tmp/venvyb53_u_a/lib/python3.9/site-packages/hsfs/feature_store.py", line 109, in from_response_json
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO -     return cls(**json_decamelized)
[2023-10-26, 21:48:23 +07] {process_utils.py:190} INFO - TypeError: __init__() missing 3 required positional arguments: 'hdfs_store_path', 'featurestore_description', and 'inode_id'
[2023-10-26, 21:48:26 +07] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 395, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 609, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path, tmp_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 463, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
__init__() missing 3 required positional arguments: 'hdfs_store_path', 'featurestore_description', and 'inode_id'
[2023-10-26, 21:48:26 +07] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=run_feature_pipeline, execution_date=20231026T144659, start_date=20231026T144705, end_date=20231026T144826
[2023-10-26, 21:48:26 +07] {standard_task_runner.py:104} ERROR - Failed to execute job 31 for task run_feature_pipeline (Process returned non-zero exit status 1.
__init__() missing 3 required positional arguments: 'hdfs_store_path', 'featurestore_description', and 'inode_id'; 3001)
[2023-10-26, 21:48:26 +07] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-26, 21:48:26 +07] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check

**Comment by minhct13** [comment]
I found out that it was an updated from Hopsworks backend to 3.4.1, changed the Hopsworks version to 3.4.* in the poetry.lock files and it worked fine.
