### ISSUE TITLE
Permissions error in training_pipeline.hyperparameter_tuning - 

### ISSUE THREAD

**Issue by jodyhuntatx** [iusztinpaul/energy-forecasting#29]
I've rerun the feature-pipeline steps and re-logged into wandb as my user w/ the API key in .env. I tried pre-creating the project with 'open' access rights with the same effect.

>> python -m training_pipeline.hyperparameter_tuning

Connected. Call `.close()` to terminate connection gracefully.

Logged in to project, explore it here https://c.app.hopsworks.ai:443/p/560278
Connected. Call `.close()` to terminate connection gracefully.
wandb: Currently logged in as: jodyhuntatx. Use `wandb login --relogin` to force relogin
wandb: ERROR Error while calling W&B API: permission denied (<Response [403]>)
Problem at: /home/demo/AIML/energy-forecasting/training-pipeline/training_pipeline/utils.py 117 init_wandb_run
wandb: ERROR It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/home/demo/.pyenv/versions/3.9.19/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/demo/.pyenv/versions/3.9.19/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/demo/AIML/energy-forecasting/training-pipeline/training_pipeline/hyperparameter_tuning.py", line 174, in <module>
    fire.Fire(run)
  File "/home/demo/.cache/pypoetry/virtualenvs/training-pipeline-Z8Uy0jSz-py3.9/lib/python3.9/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/demo/.cache/pypoetry/virtualenvs/training-pipeline-Z8Uy0jSz-py3.9/lib/python3.9/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/demo/.cache/pypoetry/virtualenvs/training-pipeline-Z8Uy0jSz-py3.9/lib/python3.9/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/demo/AIML/energy-forecasting/training-pipeline/training_pipeline/hyperparameter_tuning.py", line 50, in run
    y_train, _, X_train, _ = load_dataset_from_feature_store(
  File "/home/demo/AIML/energy-forecasting/training-pipeline/training_pipeline/data.py", line 31, in load_dataset_from_feature_store
    with init_wandb_run(
  File "/home/demo/AIML/energy-forecasting/training-pipeline/training_pipeline/utils.py", line 117, in init_wandb_run
    run = wandb.init(
  File "/home/demo/.cache/pypoetry/virtualenvs/training-pipeline-Z8Uy0jSz-py3.9/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1206, in init
    raise e
  File "/home/demo/.cache/pypoetry/virtualenvs/training-pipeline-Z8Uy0jSz-py3.9/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1187, in init
    run = wi.init()
  File "/home/demo/.cache/pypoetry/virtualenvs/training-pipeline-Z8Uy0jSz-py3.9/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 786, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)

**Comment by laxmiamrutapadhi** [comment]
The 403 error is from W&B permissions, not the pipeline. Make sure your `.env` has the correct `WANDB_API_KEY`, `WANDB_PROJECT`, and `WANDB_ENTITY`, then run `wandb login --relogin`. Also confirm your account has write access to that project in W&B.
